import Head from "next/head";
import Image from "next/image";
import Discover from "../components/discover/index.jsx";
import Footer from "../components/footer";
import Hero from "../components/hero";
import Navbar from "../components/navbar";

export default function Home() {
  return (
    <div className="">
      <Head>
        <title>DBA</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="relative flex flex-col ">
        <Navbar />
        <Hero />
        <Discover />
        <Footer />
        <Action />
      </main>
    </div>
  );
}
function Action() {
  return (
    <>
      <div className=" h-10 flex z-[200] justify-center items-center w-40 right-3 fixed text-white bottom-5 bg-blue-500 rounded-md">
        NEED HELP ?
      </div>
      <div className="fixed  text-lg h-[50px] flex z-[200] justify-center items-center w-[150px] left-5 text-white bottom-10 bg-blue-500 rounded-3xl">
        GET 15% OFF!
      </div>
    </>
  );
}
function Section() {
  return (
    <div className="flex p-5 gap-2">
      <div className="group  overflow-hidden 	">
        <img
          src="/people/1.png "
          className="transition-all duration-500 ease-in-out transform group-hover:scale-[1.008] bg-blue-200 "
        />
      </div>
      <div className="group  overflow-hidden	">
        <img
          src="/people/2.png "
          className="h-full transition-all duration-500 ease-in-out transform group-hover:scale-[1.008] bg-blue-200 "
        />
      </div>
      <div className="group  overflow-hidden	">
        <img
          src="/people/3.png "
          className="transition-all duration-500 ease-in-out transform group-hover:scale-[1.008] bg-blue-200 "
        />
      </div>
      <div className="group  overflow-hidden  	">
        <img
          src="/people/4.png "
          className="transition-all duration-500 ease-in-out transform group-hover:scale-[1.008] bg-blue-200 "
        />
      </div>
    </div>
  );
}
