import Head from "next/head";
import Image from "next/image";
import Hero from "../components/hero";
// import styles from "../styles/Home.module.css";
import Navbar from "../components/navbar";

export default function Home() {
  return (
    <div className="flex h-screen w-screen">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="flex flex-col h-screen w-screen">
        <Navbar />
        <Hero />
      </main>
    </div>
  );
}
